### ISSUE TITLE
Ignoring errors and number of bytes written when writing to websocket

### ISSUE THREAD

**Issue by tleyden** [couchbase/go-blip#19]
I noticed a few places where the number of bytes written and errors are both being ignored when writing to the underlying websocket:

https://github.com/couchbase/go-blip/blob/783feeb6e6a08e740ac764f505f20d766b4da730/sender.go#L147

and

https://github.com/couchbase/go-blip/blob/783feeb6e6a08e740ac764f505f20d766b4da730/sender.go#L223

I'm not sure what the implications are (if any)

**Comment by snej** [comment]
As far as I know, a WebSocket Connection can never do a partial write. The semantics are that each Write call sends a WebSocket message; so sending an array in two Writes is not the same thing as sending it in one.

The code should check errors, though.
