### ISSUE TITLE
Update WebSocket protocol to “BLIP_3"

### ISSUE THREAD

**Issue by snej** [couchbase/go-blip#24]
The `Sec-WebSocket-Protocol` value being sent in the WebSocket handshake is currently `BLIP_3a2`. For the release we should change it to `BLIP_3`, both because it's the final version 3 of BLIP, and to prevent anyone trying to use the GA release of CBL with a beta of SG or vice versa.

(The flip side of this is couchbase/couchbase-lite-core#411. Both commits will need to be pushed at the same time, of course.)

**Comment by snej** [comment]
I'm thinking it would be even better to append an identifier for the Couchbase Mobile replication protocol, with a version. Like "`BLIP_3+CBMobile_2`". Just in case anyone uses BLIP for any other purpose.

**Comment by snej** [comment]
Cool. Have you updated the submodule in SG too?

**Comment by tleyden** [comment]
Yep -- so to speak.  The PR to update the SG manifest + code to pass in the new app protocol id is here: https://github.com/couchbase/sync_gateway/pull/3325
